services:
  - type: web
    name: syncstate-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    envVars:
      -  key: NODE_ENV
         value: production
    # Explicitly runs compiled JavaScript from dist/ folder
