services:
  - type: web
    name: syncstate-api
    env: node
    plan: free
    root: .
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production

    # Explicitly runs compiled JavaScript from dist/ folder
